"""Add country column to alumni

Revision ID: 00c4282cecf7
Revises: b3d02015cfa1
Create Date: 2026-03-14 00:12:05.766601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c4282cecf7'
down_revision = 'b3d02015cfa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=True))
        batch_op.drop_column('lat')
        batch_op.drop_column('lon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lon', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
